services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-partyshare}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-partyshare}"]
      interval: 5s
      timeout: 5s
      retries: 12

  bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    command: sh -c "alembic upgrade head && python -m partyshare.bot"
    volumes:
      - .:/app

volumes:
  pgdata:

